export struct TrackRel {
    id: int,
    title: string,
}

export struct AlbumRel {
    id: int,
    title: string,
    assoc_track: [TrackRel],
}

export struct ArtistRel {
    id: int,
    title: string,
    assoc_album: [AlbumRel],
}

export global TrackList {
    in property <[ArtistRel]> artists;
}

export component MainWindow inherits Window {
    Text {
        text: "hello world";
        color: green;
    }
}