import { ListView, VerticalBox, Button } from "std-widgets.slint";

export struct TrackRel {
    id: int,
    title: string,
}

export struct AlbumRel {
    id: int,
    title: string,
    assoc_track: [TrackRel],
}

export struct ArtistRel {
    id: int,
    title: string,
    assoc_album: [AlbumRel],
}

export global TrackList {
    in property <[ArtistRel]> artists;
    callback populate_artists();
    callback toggle_upload();
}

export component MainWindow inherits Window {
    VerticalLayout {
        HorizontalLayout {
            Button {
                text: "Refresh";
                clicked => { TrackList.populate_artists() }
            } 

            Button {
                text: "Upload";
                clicked => { TrackList.toggle_upload() }
            }
        }

        ListView {
            for artist[index] in TrackList.artists: VerticalBox {
        	    Rectangle {
                background: Colors.red;
        	    Text {
                    text: artist.title;
                }
        	    }
                
                for album[index] in artist.assoc_album: VerticalBox {
                    Rectangle {
        		background: Colors.blue;
                        
        		Text {
                        text: album.title;
                    }}
        	   	
        		for track[index] in album.assoc_track:  
                    VerticalBox {
                        Rectangle{
                        background: Colors.green;
                	    Text {
                	        text: track.title;
                	    }
        		    }
                    }
                }
            }
        }
    }
}